// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MaintenanceMode: typeof import('./components/MaintenanceMode.vue')['default']
    NodeCard: typeof import('./components/NodeCard.vue')['default']
    NodeSelector: typeof import('./components/NodeSelector.vue')['default']
    OutboundForm: typeof import('./components/OutboundForm.vue')['default']
    OutboundManagement: typeof import('./components/OutboundManagement.vue')['default']
    RoutingManagement: typeof import('./components/RoutingManagement.vue')['default']
    RoutingRuleForm: typeof import('./components/RoutingRuleForm.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    ShadowsocksForm: typeof import('./components/ProtocolForm/ShadowsocksForm.vue')['default']
    StreamSettingsForm: typeof import('./components/ProtocolForm/StreamSettingsForm.vue')['default']
    TopologyCanvas: typeof import('./components/TopologyCanvas.vue')['default']
    TrojanForm: typeof import('./components/ProtocolForm/TrojanForm.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
    UserManagement: typeof import('./components/UserManagement.vue')['default']
    UserMapping: typeof import('./components/UserMapping.vue')['default']
    VLESSForm: typeof import('./components/ProtocolForm/VLESSForm.vue')['default']
    VMessForm: typeof import('./components/ProtocolForm/VMessForm.vue')['default']
  }
}

export { }
